### ISSUE TITLE
List of Milestones

### ISSUE THREAD

**Issue by DyfanJones** [DyfanJones/noctua#51]
# v-1.6.0

## New Features:

- [x] local caching of AWS Athena queries to reduce AWS Athena costs RAthena: [# 81](https://github.com/DyfanJones/RAthena/issues/81)

## Bug:

- [x] Region_name parameter not correctly being parsed in `dbConnect` #69

# v-1.5.1

## Bug:

- [x] sql-translate-env R functions `paste/paste0` defaulted to `concat_ws`
- [x] `data.table` due to `fwrite` supporting compression in (>=1.12.4) dependency needs to be altered to reflect this
- [x] sql-translate-env correctly translate data variables
- [x] `dbWriteTable` utilise existing s3 location when appending
- [x] `db_compute` to take into account schema and name from a string 
- [x] Polling issue resulting in `ThrottlingException: Rate exceeded` #58
- [x] sql-translate-env R functions `paste/paste0` defaulted to `concat_ws`

# v-1.5.0

## New Features:

- [x]  Added a method to integrate into RStudio connection tab
- [x] Return amount of data scanned by aws athena
- [x] Ability to change back end file parser from data.table to vroom

## Documentation
- [x] Update `roxygen2` from 6.1.1 to 7.0.2
- [x] Update `pkgdown::site` documentation with new `roxygen2`

# v-1.4.0

## New Features:

- [x] Support environment variable `AWS_ATHENA_WORK_GROUP`
- [x] Convert default delimited file from `csv` to `tsv`. This is to enable array and json to be pushed to Athena from R
- [x] Added Append checker. This checks what file type is currently being used, utilities file type when pushing new data to existing AWS Athena Table.
- [x] `dbRemoveTable` to be able to delete Athena table s3 files

## Bug:

- [x] `sql_translate_env` Integer miss classified
- [x] data.frames with row.names returning `NA` when uploading to Athena
- [x] Issue with special characters not being correctly passed to Athena
- [x] Create time stamp field incorrectly passed from Athena to R when returned alone

## Changes:

- [x] remove setting column names to lower case

## Documentation:

- [x] R documentation for new features
- [x] Update pkgdown site documentation

**Comment by DyfanJones** [comment]
# list of extra mile stones
- [ ] Add support for `JSON` class in default parser
- [ ] Added a method to integrate into RStudio connection tab

**Comment by DyfanJones** [comment]
version 1.5.1 has now been pushed to the cran
